name: Build, Scan and push Docker images
description: Thin wrapper around docker/build-push-action to scan docker images using TruffleHog
author: rudderlabs

inputs:
  build-args:
    description: "List of build-time variables"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
  file:
    description: "Path to the Dockerfile"
    required: false
  labels:
    description: "List of metadata for an image"
    required: false
  load:
    description: "Load is a shorthand for --output=type=docker"
    required: false
    default: "false"
  platforms:
    description: "List of target platforms for build"
    required: false
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: "false"
  sbom:
    description: "Generate SBOM attestation for the build (shorthand for --attest=type=sbom)"
    required: false
  secret-envs:
    description: "List of secret env vars to expose to the build (e.g., key=envname, MY_SECRET=MY_ENV_VAR)"
    required: false
  tags:
    description: "List of tags"
    required: false

outputs:
  imageid:
    description: "Image ID"
    value: ${{ steps.build-and-push.outputs.imageid }}
  digest:
    description: "Image digest"
    value: ${{ steps.build-and-push.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.build-and-push.outputs.metadata }}

runs:
  using: "composite"
  steps:
    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platform }}
        push: false
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        build-args: ${{ inputs.build-args }}
        sbom: ${{ inputs.sbom }}
        secret-envs: ${{ inputs.secret-envs }}
        outputs: type=docker,dest=${{ runner.temp }}/local-docker-image.tar
        cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache,mode=max,tag=temp

    - name: Scan docker image with TruffleHog
      shell: bash
      run: |
        docker pull trufflesecurity/trufflehog:latest
        docker run --rm -v ${{ runner.temp }}:/tmp \
          trufflesecurity/trufflehog:latest \
          docker --image file:///tmp/local-docker-image.tar \
          --github-actions \
          --no-verification \
          --fail

    - name: Build and push
      id: build-and-push
      if: success()
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platform }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        build-args: ${{ inputs.build-args }}
        sbom: ${{ inputs.sbom }}
        secret-envs: ${{ inputs.secret-envs }}
        cache-from: type=local,src=${{ runner.temp }}/.buildx-cache,tag=temp

    - name: Sign the images with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: ${{ inputs.tags }}
      shell: bash
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign  --yes ${images}